import os
import glob
import csv

#######EXTRACT HAPLOTYPES STEP 3#######
# This script simply takes as input the text files generated by script2 and adds FASTA headers
# for each haplotype (for each line). 

# Specify and set the path to the working directory
directory_path = "/scratch/125-emmer/MartaOrtigas/pysam/SNPs/SNPs_ancient/haplotypes_NOtrans_txts"
os.chdir(directory_path)

for file in glob.glob("*Hap*"):
	input_file = file
	name_file = file.split('.')[0]
	output_fasta = f"{name_file}.fasta"

	# Open the file
	with open(input_file, "r") as inp:
		with open(output_fasta, "w") as out:
			count = 0
			for haplotype in inp:
				count += 1
				fasta_format_string = f">Indiv_{count}\n{haplotype}"
				out.write(fasta_format_string)
